# Generated by Django 2.0 on 2018-03-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('article', models.TextField(max_length=2000)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('constraints', models.TextField(max_length=500)),
                ('input_Format', models.TextField(max_length=500)),
                ('output_Format', models.TextField(max_length=500)),
                ('example', models.TextField(max_length=500)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
